"""Models for downstream IC repositories."""

from pydantic import BaseModel, computed_field


class DownstreamRepo(BaseModel):
    """A downstream IC repository generated by sram-forge."""

    name: str
    """Repository name (e.g., 'gf180mcu-ic-1x1-sram-u8b24k')."""

    owner: str
    """GitHub owner/organization (e.g., 'mithro')."""

    sram: str
    """SRAM identifier for display (e.g., 'u8b24k')."""

    slot: str
    """Slot size (e.g., '1x1', '0p5x0p5')."""

    config: str
    """Path to chip config YAML in sram-forge repo."""

    deploy_key_secret: str
    """GitHub Actions secret name for deploy key."""

    @computed_field
    @property
    def full_name(self) -> str:
        """Full GitHub repository name (owner/repo)."""
        return f"{self.owner}/{self.name}"
